/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations, useVideoTexture } from '@react-three/drei';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

const DemoComputer = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/laptop-01.glb');
  const { actions } = useAnimations(animations, group);
  console.log(nodes, materials)

  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4', { 
    onloadedmetadata: function() {
      console.log(this)
        console.log('new width', this.videoWidth / this.videoHeight, "width:", this.videoWidth, "height:", this.videoHeight);
        setWidth(this.videoHeight / this.videoWidth);
    }});

  useEffect(() => {
    if (txt) {
      // txt.flipY = false;
      // txt.flipX = true;
    }
  }, [txt]);

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txt]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh
          name="Frame_ComputerFrame_0"
          // castShadow
          // receiveShadow
          geometry={nodes['Frame_ComputerFrame_0'].geometry}
          material={nodes['Frame_ComputerFrame_0'].material}
          position={[0.00, 0.98, 0.00]}
          rotation={[-1.57, 0.00, 0.00]}
          scale={[10.00, 10.00, 10.00]}>
          {/* <meshBasicMaterial map={txt} toneMapped={false} /> */}
        </mesh>
        <mesh
          name="Screen_ComputerScreen_0"
          // castShadow
          // receiveShadow
          geometry={nodes['Screen_ComputerScreen_0'].geometry}
          material={nodes['Screen_ComputerScreen_0'].material}
          position={[0.00, 0.98, -1.00]}
          rotation={[3.14, -0.00, -3.14]}
          scale={[10.00, 10.00, 10.00]}>
          <meshBasicMaterial map={txt} toneMapped={false} />
        </mesh>
        <group name="RootNode" position={[0, 1.093, 0]} rotation={[-Math.PI / 2, 0, -0.033]} scale={0.045}>
          <group
            name="Frame_ComputerFrame_0"
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.00, 1.00, 1.00]}
          />
          <group
            name="Screen_ComputerScreen_0"
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[1.00, 1.00, 0.50]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/laptop-01.glb');

export default DemoComputer;
